[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "bowbend"
requires-python = ">=3.8"
dependencies = ["cffi", "janus"]

[tool.maturin]
bindings = "cffi"
sdist-include = ["target/header.h"]